language: cpp
sudo: false

env:
    - BUILD_NAME=serial  WITH_DISTRIBUTED=serial
    - BUILD_NAME=mpi     WITH_DISTRIBUTED=mpi

matrix:
  include:
    - os: osx
      osx_image: xcode10
      env:
        - MATRIX_EVAL="brew install gcc@6 && brew link --force --overwrite gcc@6 && CC=gcc-6 && CXX=g++-6"
      compiler: gcc

    - os: osx
      osx_image: xcode10
      env:
        - MATRIX_EVAL="brew install gcc@7 && brew link --force --overwrite gcc@7 && CC=gcc-7 && CXX=g++-7"
      compiler: gcc

    - os: osx
      osx_image: xcode10
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
      compiler: clang

    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - openmpi-bin
            - libopenmpi-dev
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
      compiler: gcc-6

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - openmpi-bin
            - libopenmpi-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      compiler: gcc-7

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
            - openmpi-bin
            - libopenmpi-dev
      env:
        - MATRIX_EVAL="CC=clang-3.8 && CXX=clang++-3.8"
      compiler: clang-3.8

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export HOMEBREW_NO_AUTO_UPDATE=1; brew cask uninstall --force oclint; fi
  - eval "${MATRIX_EVAL}"

script: source ./scripts/travis/build.sh

notifications:
  email:
    recipients:
      - a.kuesters@fz-juelich.de
    on_success: never
    on_failure: always
