language: cpp
sudo: false

os:
  - osx
  - linux

osx_image: xcode10
dist: trusty

addons:
  homebrew:
    packages:
      - gcc@6
      - gcc@7
  apt:
    sources: 
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - openmpi-bin
      - libopenmpi-dev
      - g++-6
      - g++-7
      - clang-3.8

env:
  - BUILD_NAME=serial WITH_DISTRIBUTED=serial
  - BUILD_NAME=mpi WITH_DISTRIBUTED=mpi
  - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
  - MATRIX_EVAL="CC=clang && CXX=clang++"
  - MATRIX_EVAL="CC=clang-3.8 && CXX=clang++-3.8"

compiler:
  - gcc
  - clang
# - gcc-6
# - gcc-7
# - clang-3.8

matrix:
  exclude: 
    - os: osx
      addons: apt
      env: MATRIX_EVAL="CC=clang-3.8 && CXX=clang++-3.8"
    - os: linux
      addons: homebrew
      env: MATRIX_EVAL="CC=clang && CXX=clang++"
    - compiler: gcc
      env: 
        - MATRIX_EVAL="CC=clang && CXX=clang++"
        - MATRIX_EVAL="CC=clang-3.8 && CXX=clang++-3.8"
    - compiler: clang
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7" 

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export HOMEBREW_NO_AUTO_UPDATE=1; brew cask uninstall --force oclint; rm /usr/local/include/c++; fi
  - if [[ ( "$TRAVIS_OS_NAME" == "osx" ) && ( "$WITH_DISTRIBUTED" == "mpi" ) ]]; then brew install open-mpi; fi
  - eval "${MATRIX_EVAL}"

script: source ./scripts/travis/build.sh

notifications:
  email:
    recipients:
      - a.kuesters@fz-juelich.de
    on_success: never
    on_failure: always
