language: cpp
sudo: false

matrix:
  include:
    - os: osx
      osx_image: xcode10
      addons:
        homebrew:
          packages:
            - gcc@6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
        - BUILD_NAME=serial  WITH_DISTRIBUTED=serial

    - os: osx
      osx_image: xcode10
       addons:
          homebrew:
            packages:
              - gcc@7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - BUILD_NAME=serial  WITH_DISTRIBUTED=serial

    - os: osx
      osx_image: xcode10
      env:
        # On OS X, gcc is an alias for clang, and g++ is an alias for clang++
        - MATRIX_EVAL="CC=gcc && CXX=g++"
        - BUILD_NAME=serial  WITH_DISTRIBUTED=serial

    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
        - BUILD_NAME=serial  WITH_DISTRIBUTED=serial

before_install:
  - eval "${MATRIX_EVAL}"

script: source ./scripts/travis/build.sh
