language: cpp
sudo: false
os:
  - linux
  - osx
compiler: gcc

#env:
#    - BUILD_NAME=serial  WITH_DISTRIBUTED=serial

matrix:
  include:
    - os: osx
      env:
        - MATRIX_EVAL="CC=`which gcc` && CXX=`which g++`"

before_install:
    - eval "${MATRIX_EVAL}"

script: source ./scripts/travis/build.sh
